files: (^src/)|(requirements.*)
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic==1.10.11
          - types-cachetools==5.3.0.5

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
        stages:
          - commit
          - push
      - id: check-merge-conflict
        stages:
          - push
      - id: double-quote-string-fixer
        stages:
          - commit
          - push
      - id: trailing-whitespace
        stages:
          - commit
          - push
      - id: end-of-file-fixer
        stages:
          - commit
          - push

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.0
    hooks:
      - id: add-trailing-comma
        stages:
          - commit
          - push

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [ Flake8-pyproject ]
        stages:
          - commit
          - push
        args: [ --config, pyproject.toml ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages:
          - commit
          - push

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.5
    hooks:
      - id: pycln
        stages:
          - commit
          - push
        args: [ --config, pyproject.toml ]

  - repo: https://github.com/jazzband/pip-tools
    rev: 7.0.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements-lint.in
        args: [ requirements-lint.in, --output-file, requirements-lint.txt]
        files: ^requirements-lint\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements.in
        args: [ requirements.in ]
        files: ^requirements\.(in|txt)$

