[tool.black]
line-length = 120
target-version = ['py310']
include = '/src'
skip-string-normalization = true

[tool.isort]
profile = "black"
atomic = true

[tool.pycln]
path = "src"
expand_stars = true
all = true
disable_all_dunder_policy = false

[tool.flake8]
max-line-length = 120
count = true

[tool.mypy]
plugins = ["pydantic.mypy"]
python_version = "3.10"
exclude = ['venv', '.venv', 'migrations', 'scripts']
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
check_untyped_defs = true
disallow_untyped_defs = true
show_error_context = true
pretty = true
ignore_missing_imports = true
